# -*- coding: utf-8 -*-
"""mapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElS5UD5EI1kz32Oi6Vb3u8FIqI0s55Ju
"""

"""mapper.py"""

import sys

for line in sys.stdin:
  city_name = "-"
  city_population = "0"
  restaurant_name = "-"

  line = line.strip()
  splits = line.split(",")
  if len(splits) == 2:
    city_population = splits[0]
    city_name = splits[1]
  elif len(splits) == 42:
    city_name = splits[6]
    restaurant_name = splits[1]
    if city_name == "" or restaurant_name.startswith('"'):
      continue
  print(city_name, "\t", restaurant_name, "\t",  city_population)