# -*- coding: utf-8 -*-
"""reducer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElS5UD5EI1kz32Oi6Vb3u8FIqI0s55Ju
"""

"""reducer.py"""

import sys
import string

last_city_name = None
cur_city_population = "0"

for line in sys.stdin:
  line = line.strip()
  try:
    city_name,restaurant_name,city_population = line.split("\t")
  except:
    continue

  if not last_city_name or last_city_name != city_name:
    last_city_name = city_name
    cur_city_population = city_population
  elif last_city_name == city_name:
    print(city_name, "\t", restaurant_name, "\t", cur_city_population)